services:
  nginx:
    image: nginx:1.25-alpine
    expose: ["80"]
    environment:
      CONTAINER_DOCROOT: ${CONTAINER_DOCROOT:?err}
    volumes:
      - ${PROJECT_ROOT:?err}:${CONTAINER_SITE_ROOT:?err}:ro
      - ./docker/nginx.conf.tmpl:/etc/nginx/templates/default.conf.template:ro
    depends_on: [apache]
    networks:
      default:
      shared-gateway:
        aliases:
          - ${WEB_NETWORK_ALIAS:?err}

  apache:
    build:
      context: ./docker/apache
      args:
        PHP_VERSION: ${PHP_VERSION:-8.5}
    expose: ["9000"]
    working_dir: ${CONTAINER_DOCROOT:?err}
    volumes:
      - ${PROJECT_ROOT:?err}:${CONTAINER_SITE_ROOT:?err}

  mariadb:
    image: mariadb:${MYSQL_VERSION:-10.6}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - db_data:/var/lib/mysql
    ports: ["${MYSQL_PORT:-3306}:3306"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
    ports: ["${PMA_PORT:-8081}:80"]

networks:
  shared-gateway:
    name: ${SHARED_GATEWAY_NETWORK:-twentyi-shared}
    external: true

volumes:
  db_data: